services:
  postgres:
    container_name: olmosmicro-db
    image: postgres
    environment:
      POSTGRES_USER: olmosbek
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/olmosmicro-db
    ports:
      - "5435:5432"
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
volumes:
  postgres: