server:
  port: 8080
spring:
  application:
    name: customer
  banner:
    image:
      location: banner.txt
  datasource:
    url: jdbc:postgresql://localhost:5435/olmosbek?currentSchema=public
    username: olmosbek
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true